# Generated by Django 5.2.4 on 2025-07-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=180)),
                ('contact', models.CharField(max_length=180)),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
    ]
